default_platform(:android)

platform :android do

    desc "Lane for distributing app using Firebase App Distributions"
    lane :distribute do
        firebase_app_distribution(
            firebase_cli_token: ENV["FIREBASE_TOKEN"],
            app: ENV['FIREBASE_APP_ID'],
            release_notes: "last build",
            groups: "tester",
            debug: true,
            android_artifact_type: "APK",
            firebase_cli_path: "/usr/local/bin/firebase",
            apk_path: '../build/app/outputs/flutter-apk/app-debug.apk'
        )
    end


end