name: Flutter

#on:
#  pull_request:
#    types:
#      - labeled
on:
  push:
    branches: [ main ]

jobs:
  build:
#    if: github.event.label.name == 'Deliverfastelane'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Clean Flutter Dependencies.
        run: flutter clean

      - name: Get Flutter Dependencies.
        run: flutter pub get

      - name: Build Gradle
        run: flutter build apk --debug
      - run: ls build/app/outputs/flutter-apk

      - name: Set up Fastlane
        run: gem install fastlane -NV --user-install

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Grant Permission to Execute
        run: chmod +x android/gradlew

      - name: Set environment variables from secrets
        run: |
          echo "FIREBASE_APP_ID=${{ secrets.APP_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV



      #      - run: ls build/app/outputs/bundle/release


      - name: Setup and Run Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: 'android'


      - name: Distribute app with 🔥 App Distribution 🚀
        run: bundle exec fastlane distribute