name: Flutter

on:
  pull_request:
    types:
      - labeled

jobs: 
  build:
    if: github.event.label.name == 'Deliverfastelane'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Clean Flutter Dependencies.
        run: flutter clean

      - name: Get Flutter Dependencies.
        run: flutter pub get

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Cache Ruby - Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3



      - name: Set environment variables from secrets
        run: |
          echo "FIREBASE_APP_ID=${{ secrets.APP_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV



      - name: Build Gradle
        run: flutter build apk --debug
      - run: ls build/app/outputs/flutter-apk
      #      - run: ls build/app/outputs/bundle/release

      - name: Distribute app with 🔥 App Distribution 🚀
        run: bundle exec fastlane distribute
