name: Flutter

on:  #events (push and pull_request)
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:   #here we specify the jobs - We could have multiple jobs
  build:  #name it something meaningful
    runs-on: ubuntu-latest   #runner: select a machine to use

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'


      - name: Read values from appConfig.dart
        id: read-config
        run: |
          echo "PACKAGE_NAME=\$(grep 'String packageName' lib/appConfig.dart | awk -F \"'\" '{print \$2}')" >> $GITHUB_ENV
          echo "APP_NAME=\$(grep 'String appName' lib/appConfig.dart | awk -F \"'\" '{print \$2}')" >> $GITHUB_ENV
          echo "APP_ICON=\$(grep 'String appIcon' lib/appConfig.dart | awk -F \"'\" '{print \$2}')" >> $GITHUB_ENV

      - name: Debugging Steps
        run: |
          cat lib/appConfig.dart
          cat android/app/src/main/AndroidManifest.xml
          echo "PACKAGE_NAME: ${{ env.PACKAGE_NAME }}"
          echo "APP_NAME: ${{ env.APP_NAME }}"
          echo "APP_ICON: ${{ env.APP_ICON }}"

      - name: Change app name
        run: |
          set -x
          sed -i "s/android:label=\"ci_cd\"/android:label=\"$APP_NAME\"/" android/app/src/main/AndroidManifest.xml
          set +x

      - name: Change package name
        run: |
         
          flutter pub get
          flutter pub run change_app_package_name:main $PACKAGE_NAME

      - name: Check Directory Contents
        run: ls -R assets/icon


      - name: Update pubspec.yaml
        run: |
          sed -i "s|image_path:.*|image_path: \"$ICON_PATH\"|" pubspec.yaml
          if ! grep -q 'image_path:' pubspec.yaml; then
             echo "flutter_icons section not found, adding..."
             echo "flutter_icons:" >> pubspec.yaml
             echo "  android: true" >> pubspec.yaml
             echo "  ios: true" >> pubspec.yaml
             echo "  image_path: \"$ICON_PATH\"" >> pubspec.yaml
          else
             echo "flutter_icons section found, no changes needed."
          fi
          flutter pub get
          flutter pub run flutter_launcher_icons:main


      - name: Build Gradle
        run: flutter build apk --debug
      - run: ls build/app/outputs/flutter-apk
#      - run: ls build/app/outputs/bundle/release
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}}
          token: ${{secrets.TOKEN}}
          groups: tester
          file: build/app/outputs/flutter-apk/app-debug.apk