name: Flutter

on:  #events (push and pull_request)
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:   #here we specify the jobs - We could have multiple jobs
  build:  #name it something meaningful
    runs-on: ubuntu-latest   #runner: select a machine to use

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'


      - name: Change app name
        run: |
          set -x
          sed -i 's/android:label="ci_cd"/android:label="Actions"/' android/app/src/main/AndroidManifest.xml
          set +x

      - name: Build Gradle
        run: flutter build apk --debug
      - run: ls build/app/outputs/flutter-apk
      # - run: ls build/app/outputs/bundle/release
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}}
          token: ${{secrets.TOKEN}}
          groups: tester
          file: build/app/outputs/flutter-apk/app-debug.apk