name: Flutter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'


      - name: Extract values from appConfig.dart
        id: extract-values
        run: |
          APP_NAME=$(grep 'String appName' lib/appConfig.dart | awk -F '=' '{print $2}' | tr -d ' ";')
          PACKAGE_NAME=$(grep 'String packageName' lib/appConfig.dart | awk -F '=' '{print $2}' | tr -d ' ";')
          APP_ICON=$(grep 'String appIcon' lib/appConfig.dart | awk -F '=' '{print $2}' | tr -d ' ";')
          VERSION_NUMBER=$(grep 'String versionNumber' lib/appConfig.dart | awk -F '= ' '{print $2}' | tr -d ' ";')
          
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "APP_ICON=$APP_ICON" >> $GITHUB_ENV

      - name: Debugging Steps
        run: |
          cat lib/appConfig.dart
          echo "PACKAGE_NAME: ${{ env.PACKAGE_NAME }}"
          echo "APP_NAME: ${{ env.APP_NAME }}"
          echo "APP_ICON: ${{ env.APP_ICON }}"
          echo "VERSION_NUMBER: ${{ env.VERSION_NUMBER }}"


      - name: Change app name
        run: |
          set -x
          sed -i "s/android:label=\"ci_cd\"/android:label=\"${{ env.APP_NAME }}\"/" android/app/src/main/AndroidManifest.xml
          set +x
      

      - name: Change package name
        run: |
          flutter pub get
          flutter pub run change_app_package_name:main ${{ env.PACKAGE_NAME }}
      

      - name: Check Directory Contents
        run: ls -R assets/icon


      - name: Update pubspec.yaml
        run: |
          sed -i "s|image_path:.*|image_path: \"assets/icon/${{ env.APP_ICON }}\"|" pubspec.yaml
          if ! grep -q 'image_path:' pubspec.yaml; then
             echo "flutter_icons section not found, adding..."
             echo "flutter_icons:" >> pubspec.yaml
             echo "  android: true" >> pubspec.yaml
             echo "  ios: true" >> pubspec.yaml
             echo "  image_path: \"${{ env.APP_ICON }}\"" >> pubspec.yaml
          else
             echo "flutter_icons section found, no changes needed."
          fi
          flutter pub get
          flutter pub run flutter_launcher_icons:main
          

      - name: Update pubspec.yaml with version from appConfig.dart
        run: |
            sed -i "s/version: .*+/version: $VERSION_NUMBER/" pubspec.yaml
            flutter pub get



      - name: Build Gradle
        run: flutter build apk --debug
      - run: ls build/app/outputs/flutter-apk
#      - run: ls build/app/outputs/bundle/release
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}}
          token: ${{secrets.TOKEN}}
          groups: tester
          file: build/app/outputs/flutter-apk/app-debug.apk