name: Flutter

on:  #events (push and pull_request)
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:   #here we specify the jobs - We could have multiple jobs
  build:  #name it something meaningful
    runs-on: ubuntu-latest   #runner: select a machine to use

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Read Config File
        id: read-config
        run: echo "CONFIG=$(cat config.json | tr -d '\n')" >> $GITHUB_ENV


#      - name: Change app name
#        run: |
#          set -x
#          sed -i "s/android:label=\"ci_cd\"/android:label=\"$CONFIG.appName\"/" android/app/src/main/AndroidManifest.xml
#          set +x

      - name: Change app name
        run: |
          set -x
          sed -i 's/android:label="ci_cd"/android:label=$CONFIG.appName/' android/app/src/main/AndroidManifest.xml
          set +x


      - name: Change package name
        run: |
          flutter pub get
          flutter pub run change_app_package_name:main $CONFIG.packageName

#      - name: Change package name
#        run: |
#          flutter pub get
#          flutter pub run change_app_package_name:main com.example.ci_cd

#      - name: Check Directory Contents
#        run: ls -R assets/icon

#      - name: Set Permissions for Image File
#        run: sudo chown $USER:$USER "assets/icon/$(echo $CONFIG | jq -r .iconPath)"

      - name: Set Permissions for Image File
        run: sudo chown $USER:$USER "assets/icon/desk_icon.png"

#      - name: Update pubspec.yaml
#        run: |
#          ICON_PATH="assets/icon/$(echo $CONFIG | jq -r .iconPath)"
#          sed -i "s|image_path:.*|image_path: \"$ICON_PATH\"|" pubspec.yaml
#          if ! grep -q 'image_path:' pubspec.yaml; then
#             echo "flutter_icons section not found, adding..."
#             echo "flutter_icons:" >> pubspec.yaml
#             echo "  android: true" >> pubspec.yaml
#             echo "  ios: true" >> pubspec.yaml
#             echo "  image_path: \"$ICON_PATH\"" >> pubspec.yaml
#          else
#             echo "flutter_icons section found, no changes needed."
#          fi
#          flutter pub get
#          flutter pub run flutter_launcher_icons:main
      
      

      - name: Update pubspec.yaml
        run: |
          sed -i 's|image_path:.*|image_path: "assets/icon/desk_icon.png"|' pubspec.yaml
          if ! grep -q 'image_path:' pubspec.yaml; then
            echo "flutter_icons section not found, adding..."
            echo "flutter_icons:" >> pubspec.yaml
            echo "  android: true" >> pubspec.yaml
            echo "  ios: true" >> pubspec.yaml
            echo '  image_path: "assets/icon/desk_icon.png"' >> pubspec.yaml
          else
            echo "flutter_icons section found, no changes needed."
          fi
          flutter pub get
          flutter pub run flutter_launcher_icons:main

#      - name: Build Android
#        run: cd android && ./gradlew assembleDebug
#        working-directory: ./android

      - name: Build Gradle
        run: flutter build apk --debug
      - run: ls build/app/outputs/flutter-apk
#      - run: ls build/app/outputs/bundle/release
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}}
          token: ${{secrets.TOKEN}}
          groups: tester
          file: build/app/outputs/flutter-apk/app-debug.apk